model: "dqn"

env:
    env_name: "test_environment"
    overwrite_render: True
    record: False # important: must be set to false!
    high: 255.

output:
    output_path: &output_path "results/q6_dqn/"
    model_output: !join [*output_path, "model.weights.pt"]
    log_path: !join [*output_path, "log.txt"]
    plot_output: !join [*output_path, "scores.png"]

model_training:
    num_episodes_test: 20
    grad_clip: True
    clip_val: 10
    saving_freq: 5000
    log_freq: 50
    eval_freq: 1000
    soft_epsilon: 0
    device: "gpu" # cpu/gpu
    compile: False
    compile_mode: "default"

hyper_params:
    nsteps_train: 10000
    batch_size: 32
    buffer_size: 1000
    target_update_freq: 500
    gamma: 0.99
    learning_freq: 4
    state_history: 4
    lr_begin: 0.005
    lr_end: 0.001
    lr_nsteps: 5000
    eps_begin: 1
    eps_end: 0.01
    eps_nsteps: 8000
    learning_start: 200
