model: "dqn"

env:
    env_name: "ALE/Pong-v5"
    overwrite_render: True
    record: False # use `record_episode.py` instead
    high: 255.
    render_mode: "rgb_array"

output:
    output_path: &output_path "results/q7_dqn/"
    model_output: "submission/model.weights"  # output weights to submission folder
    log_path: !join [*output_path, "log.txt"]
    plot_output: !join [*output_path, "scores.png"]
    record_path: !join [*output_path, "monitor/"]

model_training:
    load_path: "pretrained_weights/model.weights"
    num_episodes_test: 50
    grad_clip: True
    clip_val: 10
    saving_freq: 250000
    log_freq: 50
    eval_freq: 250000
    record_freq: 250000
    soft_epsilon: 0.05
    device: "gpu" # cpu/gpu
    compile: False
    compile_mode: "default"

hyper_params:
    nsteps_train: 4000000
    batch_size: 32
    buffer_size: 1000000
    target_update_freq: 10000
    gamma: 0.99
    learning_freq: 4
    state_history: 4
    skip_frame: 4
    lr_begin: 0.00008
    lr_end: 0.00005
    lr_nsteps: 500000
    eps_begin: 0.5
    eps_end: 0.1
    eps_nsteps: 1000000
    learning_start: 50000
